import { useEffect, useMemo, useState } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { Loader2, Pencil, Plus, Search } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { Button } from '@/components/ui/button'
import { DataTablePagination } from '@/components/data-table/DataTablePagination'
import { DataTableShell } from '@/components/data-table/DataTableShell'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useCategories, useSaveCategory } from '../hooks/useInventory'
import { categorySchema } from '../schemas/inventory.schemas'
import type { Category, CategoryInput } from '../types/inventory.types'

const defaults: CategoryInput = { name: '', isActive: true }
export function CategoriesPage() {
  const categoriesQuery = useCategories(); const [editing, setEditing] = useState<Category | null>(null); const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10)
  const form = useForm<CategoryInput>({ resolver: zodResolver(categorySchema), defaultValues: defaults }); const save = useSaveCategory(editing?.id ?? null)
  useEffect(() => form.reset(editing ?? defaults), [editing, form])
  const close = () => { setOpen(false); setEditing(null) }; const create = () => { setEditing(null); setOpen(true) }; const edit = (item: Category) => { setEditing(item); setOpen(true) }
  const rows = useMemo(() => { const term = search.trim().toLowerCase(); return (categoriesQuery.data?.data ?? []).filter((item) => !term || item.name.toLowerCase().includes(term)) }, [categoriesQuery.data?.data, search]); const paged = rows.slice((page - 1) * pageSize, page * pageSize)
  return <div className="flex h-full w-full flex-col space-y-6"><Header title="Product Categories" description="Group products into a simple, operational category list." action="Add category" onClick={create} /><SearchBar value={search} onChange={(value) => { setSearch(value); setPage(1) }} placeholder="Search categories" count={`${rows.length} categor${rows.length === 1 ? 'y' : 'ies'}`} /><DataTableShell><Table><TableHeader><TableRow className={head}><TableHead className="px-4">Category</TableHead><TableHead className="px-4">Status</TableHead><TableHead className="w-20 px-4 text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{categoriesQuery.isLoading ? <Loading colSpan={3} /> : paged.length === 0 ? <Empty colSpan={3} label="No categories found" onClick={create} /> : paged.map((item) => <TableRow key={item.id}><TableCell className="px-4 py-3.5 font-medium">{item.name}</TableCell><TableCell className="px-4 py-3.5"><Status active={item.isActive} /></TableCell><TableCell className="px-4 py-3.5 text-right"><Button variant="ghost" size="icon-sm" onClick={() => edit(item)} aria-label={`Edit ${item.name}`}><Pencil className="size-4" /></Button></TableCell></TableRow>)}</TableBody></Table></DataTableShell><DataTablePagination page={page} pageSize={pageSize} totalItems={rows.length} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1) }} /><Dialog open={open} onOpenChange={(value) => value ? setOpen(true) : close()}><DialogContent><DialogHeader><DialogTitle>{editing ? `Edit ${editing.name}` : 'Add category'}</DialogTitle><DialogDescription>Categories can be deactivated when they should no longer be assigned to products.</DialogDescription></DialogHeader><form onSubmit={form.handleSubmit((values) => save.mutate(values, { onSuccess: close }))} className="space-y-4"><Field label="Name" error={form.formState.errors.name?.message}><Input {...form.register('name')} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...form.register('isActive')} /> Active</label>{save.isError && <p className="text-sm text-destructive">{save.error.message}</p>}<DialogFooter><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit" disabled={save.isPending}>{save.isPending && <Loader2 className="size-4 animate-spin" />}{editing ? 'Save changes' : 'Add category'}</Button></DialogFooter></form></DialogContent></Dialog></div>
}
const head = 'border-b border-slate-200 bg-[#e9ecef]/60 text-xs uppercase tracking-wider hover:bg-[#e9ecef]/60 dark:border-slate-800 dark:bg-slate-800/60'
export function Header({ title, description, action, onClick }: { title: string; description: string; action: string; onClick: () => void }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><Button className="gap-1.5 bg-[#e05d38] text-white hover:bg-[#c94f2d]" onClick={onClick}><Plus className="size-4" />{action}</Button></div> }
export function SearchBar({ value, onChange, placeholder, count }: { value: string; onChange: (value: string) => void; placeholder: string; count: string }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><Input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-10 rounded-lg border-slate-200 bg-white pl-9 shadow-xs dark:border-slate-800 dark:bg-slate-900" /></div><p className="text-sm text-slate-500">{count}</p></div> }
export function Status({ active }: { active: boolean }) { return <span className={active ? 'inline-flex rounded bg-emerald-50 px-2 py-0.5 text-[11px] font-semibold text-emerald-600' : 'inline-flex rounded bg-slate-100 px-2 py-0.5 text-[11px] font-semibold text-slate-500'}>{active ? 'Active' : 'Inactive'}</span> }
export function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium text-slate-700 dark:text-slate-300">{label}{children}{error && <span className="text-xs font-normal text-destructive">{error}</span>}</label> }
export function Loading({ colSpan }: { colSpan: number }) { return <TableRow><TableCell colSpan={colSpan} className="h-48 text-center text-sm text-slate-500"><Loader2 className="mx-auto mb-2 size-6 animate-spin text-[#e05d38]" />Loading…</TableCell></TableRow> }
export function Empty({ colSpan, label, onClick }: { colSpan: number; label: string; onClick: () => void }) { return <TableRow><TableCell colSpan={colSpan} className="h-48 text-center"><p className="mb-3 text-sm text-slate-500">{label}</p><Button size="sm" onClick={onClick}><Plus className="size-4" />Add record</Button></TableCell></TableRow> }
