import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRightLeft, ClipboardPlus, SlidersHorizontal } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { DataTableShell } from '@/components/data-table/DataTableShell'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useStockBalances } from '../hooks/useInventory'

export function InventoryOverviewPage() {
  const [search, setSearch] = useState(''); const query = useStockBalances({ search }); const rows = query.data?.data ?? []
  return <div className="flex h-full w-full flex-col space-y-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">Stock Overview</h1><p className="mt-1 text-sm text-slate-500">Quantities and weighted-average valuation are calculated from the immutable movement ledger.</p></div><div className="flex flex-wrap gap-2"><Link to="/inventory/opening-stock/new"><Button variant="outline"><ClipboardPlus className="size-4" />Opening stock</Button></Link><Link to="/inventory/adjustments/new"><Button variant="outline"><SlidersHorizontal className="size-4" />Adjustment</Button></Link><Link to="/inventory/transfers/new"><Button className="bg-primarytext-primary-foregroundhover:bg-primary/90"><ArrowRightLeft className="size-4" />Transfer</Button></Link></div></div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search product or SKU" className="h-10 w-full rounded-lg sm:w-80" /><p className="text-sm text-slate-500">{rows.length} stock balance{rows.length === 1 ? '' : 's'}</p></div><DataTableShell><div className="overflow-x-auto"><Table><TableHeader><TableRow className={head}><TableHead className="px-4">Product</TableHead><TableHead className="px-4">Warehouse</TableHead><TableHead className="px-4">Branch</TableHead><TableHead className="px-4 text-right">Quantity</TableHead><TableHead className="px-4 text-right">Average cost</TableHead><TableHead className="px-4 text-right">Inventory value</TableHead></TableRow></TableHeader><TableBody>{query.isPending ? <TableRow><TableCell colSpan={6} className="h-40 text-center text-sm text-slate-500">Loading stock balances…</TableCell></TableRow> : rows.length === 0 ? <TableRow><TableCell colSpan={6} className="h-40 text-center text-sm text-slate-500">No stock balances found.</TableCell></TableRow> : rows.map((row) => <TableRow key={`${row.productId}-${row.warehouseId}`}><TableCell className="px-4 py-3.5"><p className="font-medium">{row.productName}</p><p className="font-mono text-xs text-slate-500">{row.sku}</p></TableCell><TableCell className="px-4 py-3.5">{row.warehouseCode} — {row.warehouseName}</TableCell><TableCell className="px-4 py-3.5">{row.branchName}</TableCell><TableCell className="px-4 py-3.5 text-right font-mono">{row.quantity} {row.unitCode}</TableCell><TableCell className="px-4 py-3.5 text-right font-mono">{row.averageCostBase.toFixed(4)}</TableCell><TableCell className="px-4 py-3.5 text-right font-mono">{row.totalValueBase.toFixed(4)}</TableCell></TableRow>)}</TableBody></Table></div></DataTableShell></div>
}
const head = 'border-b border-slate-200 bg-slate-50/80 text-xs uppercase tracking-wider hover:bg-slate-50/80 dark:border-slate-800 dark:bg-slate-800/60'
