import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { DataTableShell } from '@/components/data-table/DataTableShell'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAdjustments, useOpeningStocks, useTransfers } from '../hooks/useInventory'
import { InventoryDocumentStatus } from '../types/inventory.types'

const head = 'border-b border-slate-200 bg-slate-50/80 text-xs uppercase tracking-wider hover:bg-slate-50/80 dark:border-slate-800 dark:bg-slate-800/60'
const filters = (search: string, status: string, fromDate: string, toDate: string) => ({ documentNumber: search || undefined, status: status || undefined, fromDate: fromDate || undefined, toDate: toDate || undefined })

function Status({ value }: { value: InventoryDocumentStatus }) { const posted = value === InventoryDocumentStatus.Posted; return <span className={posted ? 'inline-flex rounded bg-emerald-50 px-2 py-0.5 text-[11px] font-semibold text-emerald-700' : 'inline-flex rounded bg-amber-50 px-2 py-0.5 text-[11px] font-semibold text-amber-700'}>{posted ? 'Posted' : 'Draft'}</span> }
function ListHeader({ title, description, newTo, newLabel }: { title: string; description: string; newTo: string; newLabel: string }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div><Link to={newTo}><Button className="bg-primarytext-primary-foregroundhover:bg-primary/90"><Plus className="size-4" />{newLabel}</Button></Link></div> }
function Filters({ search, setSearch, status, setStatus, fromDate, setFromDate, toDate, setToDate }: { search: string; setSearch: (v: string) => void; status: string; setStatus: (v: string) => void; fromDate: string; setFromDate: (v: string) => void; toDate: string; setToDate: (v: string) => void }) { return <div className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_160px_160px_160px]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Document number" /></div><select className="h-9 rounded-md border bg-background px-3 text-sm" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="0">Draft</option><option value="1">Posted</option></select><Input type="date" aria-label="From date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} /><Input type="date" aria-label="To date" value={toDate} onChange={(e) => setToDate(e.target.value)} /></div> }
function useFilters() { const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); return { search, setSearch, status, setStatus, fromDate, setFromDate, toDate, setToDate, query: filters(search, status, fromDate, toDate) } }

export function OpeningStockListPage() {
  const f = useFilters(); const query = useOpeningStocks(f.query); const rows = query.data?.data ?? []
  return <div className="flex h-full flex-col space-y-6"><ListHeader title="Opening Stock" description="Prepare, review, and post opening inventory documents." newTo="/inventory/opening-stock/new" newLabel="New opening stock" /><Filters {...f} /><DataTableShell><Table><TableHeader><TableRow className={head}><TableHead>Document</TableHead><TableHead>Date</TableHead><TableHead>Branch</TableHead><TableHead>Warehouse</TableHead><TableHead className="text-right">Lines</TableHead><TableHead className="text-right">Total value</TableHead><TableHead>Status</TableHead><TableHead>Created by</TableHead></TableRow></TableHeader><TableBody>{query.isPending ? <Loading span={8} /> : rows.length === 0 ? <Empty span={8} /> : rows.map((row) => <TableRow key={row.id} className="cursor-pointer"><TableCell><Link className="font-mono font-semibold text-primary" to={`/inventory/opening-stock/${row.id}`}>{row.documentNumber}</Link></TableCell><TableCell>{row.documentDate}</TableCell><TableCell>{row.branchName}</TableCell><TableCell>{row.warehouseName}</TableCell><TableCell className="text-right">{row.lineCount}</TableCell><TableCell className="text-right font-mono">{row.totalValueBase.toFixed(4)}</TableCell><TableCell><Status value={row.status} /></TableCell><TableCell>{row.createdByUsername}</TableCell></TableRow>)}</TableBody></Table></DataTableShell></div>
}

export function AdjustmentsListPage() {
  const f = useFilters(); const query = useAdjustments(f.query); const rows = query.data?.data ?? []
  return <div className="flex h-full flex-col space-y-6"><ListHeader title="Stock Adjustments" description="Reconcile physical counts against the system ledger." newTo="/inventory/adjustments/new" newLabel="New adjustment" /><Filters {...f} /><DataTableShell><Table><TableHeader><TableRow className={head}><TableHead>Document</TableHead><TableHead>Date</TableHead><TableHead>Branch</TableHead><TableHead>Warehouse</TableHead><TableHead>Reason</TableHead><TableHead className="text-right">Lines</TableHead><TableHead>Status</TableHead><TableHead>Created by</TableHead></TableRow></TableHeader><TableBody>{query.isPending ? <Loading span={8} /> : rows.length === 0 ? <Empty span={8} /> : rows.map((row) => <TableRow key={row.id}><TableCell><Link className="font-mono font-semibold text-primary" to={`/inventory/adjustments/${row.id}`}>{row.documentNumber}</Link></TableCell><TableCell>{row.documentDate}</TableCell><TableCell>{row.branchName}</TableCell><TableCell>{row.warehouseName}</TableCell><TableCell>{row.reason}</TableCell><TableCell className="text-right">{row.lineCount}</TableCell><TableCell><Status value={row.status} /></TableCell><TableCell>{row.createdByUsername}</TableCell></TableRow>)}</TableBody></Table></DataTableShell></div>
}

export function TransfersListPage() {
  const f = useFilters(); const query = useTransfers(f.query); const rows = query.data?.data ?? []
  return <div className="flex h-full flex-col space-y-6"><ListHeader title="Warehouse Transfers" description="Move stock between warehouses without changing company-wide value." newTo="/inventory/transfers/new" newLabel="New transfer" /><Filters {...f} /><DataTableShell><Table><TableHeader><TableRow className={head}><TableHead>Document</TableHead><TableHead>Date</TableHead><TableHead>Branch</TableHead><TableHead>Source</TableHead><TableHead>Destination</TableHead><TableHead className="text-right">Lines</TableHead><TableHead>Status</TableHead><TableHead>Created by</TableHead></TableRow></TableHeader><TableBody>{query.isPending ? <Loading span={8} /> : rows.length === 0 ? <Empty span={8} /> : rows.map((row) => <TableRow key={row.id}><TableCell><Link className="font-mono font-semibold text-primary" to={`/inventory/transfers/${row.id}`}>{row.documentNumber}</Link></TableCell><TableCell>{row.documentDate}</TableCell><TableCell>{row.branchName}</TableCell><TableCell>{row.sourceWarehouseName}</TableCell><TableCell>{row.destinationWarehouseName}</TableCell><TableCell className="text-right">{row.lineCount}</TableCell><TableCell><Status value={row.status} /></TableCell><TableCell>{row.createdByUsername}</TableCell></TableRow>)}</TableBody></Table></DataTableShell></div>
}

function Loading({ span }: { span: number }) { return <TableRow><TableCell colSpan={span} className="h-40 text-center text-muted-foreground">Loading documents…</TableCell></TableRow> }
function Empty({ span }: { span: number }) { return <TableRow><TableCell colSpan={span} className="h-40 text-center text-muted-foreground">No documents found.</TableCell></TableRow> }
