// <auto-generated />
using System;
using Api.Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807225956_InitialMvpArchitecture")]
    partial class InitialMvpArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Modules.Auth.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Finance.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ParentAccountId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Category", "\"Category\" IN (1000, 2000, 3000, 4000, 5000)");

                            t.HasCheckConstraint("CK_Accounts_NotSelfParent", "\"ParentAccountId\" IS NULL OR \"ParentAccountId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_Accounts_Type", "\"Type\" BETWEEN 0 AND 7");
                        });
                });

            modelBuilder.Entity("Api.Modules.Finance.AccountTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasFilter("\"ReversesTransactionId\" IS NOT NULL");

                    b.HasIndex("AccountId", "TransactionDateUtc");

                    b.HasIndex("ContactId", "TransactionDateUtc");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("ContactId", "AccountId", "TransactionDateUtc");

                    b.ToTable("AccountTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountTransactions_BaseCurrencyAmounts", "\"Amount\" = \"BaseAmount\"");

                            t.HasCheckConstraint("CK_AccountTransactions_NonZero", "\"Amount\" <> 0 AND \"BaseAmount\" <> 0");

                            t.HasCheckConstraint("CK_AccountTransactions_NotSelfReversal", "\"ReversesTransactionId\" IS NULL OR \"ReversesTransactionId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_AccountTransactions_SourceType", "\"SourceType\" BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("Api.Modules.Finance.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Contacts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Contacts_Type", "\"Type\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Api.Modules.Finance.CurrencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBaseCurrency")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Currencies_ExchangeRate", "\"ExchangeRate\" > 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Finance.FinancialVoucherEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VoucherDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CounterpartyAccountId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.HasIndex("Type", "Status", "VoucherDateUtc");

                    b.ToTable("FinancialVouchers", null, t =>
                        {
                            t.HasCheckConstraint("CK_FinancialVouchers_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_FinancialVouchers_DifferentAccounts", "\"AccountId\" <> \"CounterpartyAccountId\"");

                            t.HasCheckConstraint("CK_FinancialVouchers_Status", "\"Status\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_FinancialVouchers_TransferContact", "\"Type\" <> 3 OR \"ContactId\" IS NULL");

                            t.HasCheckConstraint("CK_FinancialVouchers_Type", "\"Type\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Api.Modules.Finance.PaymentAllocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FinancialVoucherId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SalesInvoiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FinancialVoucherId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex(new[] { "FinancialVoucherId", "PurchaseInvoiceId" }, "UX_PaymentAllocations_ActiveVoucherPurchaseInvoice")
                        .IsUnique()
                        .HasFilter("\"IsActive\" AND \"PurchaseInvoiceId\" IS NOT NULL");

                    b.HasIndex(new[] { "FinancialVoucherId", "SalesInvoiceId" }, "UX_PaymentAllocations_ActiveVoucherSalesInvoice")
                        .IsUnique()
                        .HasFilter("\"IsActive\" AND \"SalesInvoiceId\" IS NOT NULL");

                    b.ToTable("PaymentAllocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentAllocations_OneInvoice", "(\"SalesInvoiceId\" IS NOT NULL AND \"PurchaseInvoiceId\" IS NULL) OR (\"SalesInvoiceId\" IS NULL AND \"PurchaseInvoiceId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PaymentAllocations_Positive", "\"AllocatedAmount\" > 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockAdjustmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AdjustmentDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdjustmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentNumber")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockAdjustments_Reason", "\"Reason\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_StockAdjustments_Status", "\"Status\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockAdjustmentLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("StockAdjustmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockAdjustmentId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("StockAdjustmentLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockAdjustmentLines_Quantity", "\"Quantity\" <> 0 AND \"ConversionFactor\" > 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("QuantityBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("ReversesTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReversesTransactionId")
                        .IsUnique()
                        .HasFilter("\"ReversesTransactionId\" IS NOT NULL");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("WarehouseId", "ItemId", "TransactionDateUtc");

                    b.ToTable("StockTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockTransactions_NonZero", "\"QuantityBase\" <> 0");

                            t.HasCheckConstraint("CK_StockTransactions_NotSelfReversal", "\"ReversesTransactionId\" IS NULL OR \"ReversesTransactionId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_StockTransactions_SourceType", "\"SourceType\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Api.Modules.Inventory.WarehouseTransferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransferDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("SourceWarehouseId");

                    b.HasIndex("TransferNumber")
                        .IsUnique();

                    b.ToTable("WarehouseTransfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseTransfers_DifferentWarehouses", "\"SourceWarehouseId\" <> \"DestinationWarehouseId\"");

                            t.HasCheckConstraint("CK_WarehouseTransfers_Status", "\"Status\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Api.Modules.Inventory.WarehouseTransferLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseTransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("WarehouseTransferId");

                    b.ToTable("WarehouseTransferLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_WarehouseTransferLines_Quantity", "\"Quantity\" > 0 AND \"ConversionFactor\" > 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Purchases.PurchaseInvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OriginalPurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("OriginalPurchaseInvoiceId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("VendorId", "InvoiceDateUtc");

                    b.ToTable("PurchaseInvoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseInvoices_NotSelfReturn", "\"OriginalPurchaseInvoiceId\" IS NULL OR \"OriginalPurchaseInvoiceId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_PurchaseInvoices_ReturnLink", "(\"IsReturn\" AND \"OriginalPurchaseInvoiceId\" IS NOT NULL) OR (NOT \"IsReturn\" AND \"OriginalPurchaseInvoiceId\" IS NULL)");

                            t.HasCheckConstraint("CK_PurchaseInvoices_Status", "\"Status\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_PurchaseInvoices_Totals", "\"Subtotal\" >= 0 AND \"DiscountTotal\" >= 0 AND \"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Purchases.PurchaseInvoiceLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("OriginalPurchaseInvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OriginalPurchaseInvoiceLineId");

                    b.HasIndex("PurchaseAccountId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("PurchaseInvoiceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseInvoiceLines_Amounts", "\"Quantity\" > 0 AND \"ConversionFactor\" > 0 AND \"UnitPrice\" >= 0 AND \"DiscountAmount\" >= 0 AND \"LineTotal\" >= 0");

                            t.HasCheckConstraint("CK_PurchaseInvoiceLines_NotSelfReturn", "\"OriginalPurchaseInvoiceLineId\" IS NULL OR \"OriginalPurchaseInvoiceLineId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Api.Modules.Sales.SalesInvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InvoiceDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsReturn")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OriginalSalesInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("OriginalSalesInvoiceId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("CustomerId", "InvoiceDateUtc");

                    b.ToTable("SalesInvoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalesInvoices_NotSelfReturn", "\"OriginalSalesInvoiceId\" IS NULL OR \"OriginalSalesInvoiceId\" <> \"Id\"");

                            t.HasCheckConstraint("CK_SalesInvoices_ReturnLink", "(\"IsReturn\" AND \"OriginalSalesInvoiceId\" IS NOT NULL) OR (NOT \"IsReturn\" AND \"OriginalSalesInvoiceId\" IS NULL)");

                            t.HasCheckConstraint("CK_SalesInvoices_Status", "\"Status\" BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_SalesInvoices_Totals", "\"Subtotal\" >= 0 AND \"DiscountTotal\" >= 0 AND \"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("Api.Modules.Sales.SalesInvoiceLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid?>("OriginalSalesInvoiceLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("SalesAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OriginalSalesInvoiceLineId");

                    b.HasIndex("SalesAccountId");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("SalesInvoiceLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalesInvoiceLines_Amounts", "\"Quantity\" > 0 AND \"ConversionFactor\" > 0 AND \"UnitPrice\" >= 0 AND \"DiscountAmount\" >= 0 AND \"LineTotal\" >= 0");

                            t.HasCheckConstraint("CK_SalesInvoiceLines_NotSelfReturn", "\"OriginalSalesInvoiceLineId\" IS NULL OR \"OriginalSalesInvoiceLineId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Api.Modules.Settings.BusinessSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("BaseCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrencyDecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencySymbolPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultPayableAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefaultReceivableAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("InvoiceNumberPrefix")
                        .HasColumnType("text");

                    b.Property<bool>("IsSetupCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("NextInvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId");

                    b.HasIndex("DefaultPayableAccountId");

                    b.HasIndex("DefaultReceivableAccountId");

                    b.ToTable("BusinessSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessSettings_Singleton", "\"Id\" = '00000000-0000-0000-0000-000000000001'::uuid");
                        });
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("ItemCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemCategories_NotSelfParent", "\"ParentCategoryId\" IS NULL OR \"ParentCategoryId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("BaseUnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PurchaseAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SalesAccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitOfMeasureId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PurchaseAccountId");

                    b.HasIndex("SalesAccountId");

                    b.ToTable("Items", null, t =>
                        {
                            t.HasCheckConstraint("CK_Items_ServiceInventory", "\"Type\" <> 1 OR NOT \"TrackInventory\"");

                            t.HasCheckConstraint("CK_Items_Type", "\"Type\" BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemUnitOfMeasureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsDefaultForPurchasing")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefaultForSelling")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasureId");

                    b.HasIndex("ItemId", "UnitOfMeasureId")
                        .IsUnique();

                    b.HasIndex(new[] { "ItemId" }, "UX_ItemUnitsOfMeasure_DefaultPurchasing")
                        .IsUnique()
                        .HasFilter("\"IsDefaultForPurchasing\"");

                    b.HasIndex(new[] { "ItemId" }, "UX_ItemUnitsOfMeasure_DefaultSelling")
                        .IsUnique()
                        .HasFilter("\"IsDefaultForSelling\"");

                    b.ToTable("ItemUnitsOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Settings.UnitOfMeasureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Settings.WarehouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Api.Modules.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedLoginAttemptCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LockoutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Auth.RefreshTokenEntity", b =>
                {
                    b.HasOne("Api.Modules.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Finance.AccountEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Api.Modules.Finance.AccountEntity", "ParentAccount")
                        .WithMany()
                        .HasForeignKey("ParentAccountId");

                    b.Navigation("Currency");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("Api.Modules.Finance.AccountTransactionEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.ContactEntity", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.AccountTransactionEntity", "ReversesTransaction")
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("Currency");

                    b.Navigation("ReversesTransaction");
                });

            modelBuilder.Entity("Api.Modules.Finance.FinancialVoucherEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.ContactEntity", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.AccountEntity", "CounterpartyAccount")
                        .WithMany()
                        .HasForeignKey("CounterpartyAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Contact");

                    b.Navigation("CounterpartyAccount");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Api.Modules.Finance.PaymentAllocationEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.FinancialVoucherEntity", "FinancialVoucher")
                        .WithMany("Allocations")
                        .HasForeignKey("FinancialVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Purchases.PurchaseInvoiceEntity", "PurchaseInvoice")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Sales.SalesInvoiceEntity", "SalesInvoice")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FinancialVoucher");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockAdjustmentEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockAdjustmentLineEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Inventory.StockAdjustmentEntity", "StockAdjustment")
                        .WithMany("Lines")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StockAdjustment");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockTransactionEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Inventory.StockTransactionEntity", "ReversesTransaction")
                        .WithMany()
                        .HasForeignKey("ReversesTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ReversesTransaction");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Api.Modules.Inventory.WarehouseTransferEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("Api.Modules.Inventory.WarehouseTransferLineEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Inventory.WarehouseTransferEntity", "WarehouseTransfer")
                        .WithMany("Lines")
                        .HasForeignKey("WarehouseTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UnitOfMeasure");

                    b.Navigation("WarehouseTransfer");
                });

            modelBuilder.Entity("Api.Modules.Purchases.PurchaseInvoiceEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Purchases.PurchaseInvoiceEntity", "OriginalPurchaseInvoice")
                        .WithMany()
                        .HasForeignKey("OriginalPurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.ContactEntity", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("OriginalPurchaseInvoice");

                    b.Navigation("Vendor");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Api.Modules.Purchases.PurchaseInvoiceLineEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Purchases.PurchaseInvoiceLineEntity", "OriginalPurchaseInvoiceLine")
                        .WithMany()
                        .HasForeignKey("OriginalPurchaseInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.AccountEntity", "PurchaseAccount")
                        .WithMany()
                        .HasForeignKey("PurchaseAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Purchases.PurchaseInvoiceEntity", "PurchaseInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OriginalPurchaseInvoiceLine");

                    b.Navigation("PurchaseAccount");

                    b.Navigation("PurchaseInvoice");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Sales.SalesInvoiceEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.ContactEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Sales.SalesInvoiceEntity", "OriginalSalesInvoice")
                        .WithMany()
                        .HasForeignKey("OriginalSalesInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Settings.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("OriginalSalesInvoice");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Api.Modules.Sales.SalesInvoiceLineEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Sales.SalesInvoiceLineEntity", "OriginalSalesInvoiceLine")
                        .WithMany()
                        .HasForeignKey("OriginalSalesInvoiceLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.AccountEntity", "SalesAccount")
                        .WithMany()
                        .HasForeignKey("SalesAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Sales.SalesInvoiceEntity", "SalesInvoice")
                        .WithMany("Lines")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OriginalSalesInvoiceLine");

                    b.Navigation("SalesAccount");

                    b.Navigation("SalesInvoice");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Settings.BusinessSettingsEntity", b =>
                {
                    b.HasOne("Api.Modules.Finance.CurrencyEntity", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.AccountEntity", "DefaultPayableAccount")
                        .WithMany()
                        .HasForeignKey("DefaultPayableAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.AccountEntity", "DefaultReceivableAccount")
                        .WithMany()
                        .HasForeignKey("DefaultReceivableAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");

                    b.Navigation("DefaultPayableAccount");

                    b.Navigation("DefaultReceivableAccount");
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemCategoryEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemCategoryEntity", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "BaseUnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("BaseUnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.ItemCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.Modules.Finance.AccountEntity", "PurchaseAccount")
                        .WithMany()
                        .HasForeignKey("PurchaseAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Api.Modules.Finance.AccountEntity", "SalesAccount")
                        .WithMany()
                        .HasForeignKey("SalesAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnitOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("PurchaseAccount");

                    b.Navigation("SalesAccount");
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemUnitOfMeasureEntity", b =>
                {
                    b.HasOne("Api.Modules.Settings.ItemEntity", "Item")
                        .WithMany("AdditionalUnits")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Settings.UnitOfMeasureEntity", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("Api.Modules.Finance.FinancialVoucherEntity", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Api.Modules.Inventory.StockAdjustmentEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Api.Modules.Inventory.WarehouseTransferEntity", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Api.Modules.Purchases.PurchaseInvoiceEntity", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("Api.Modules.Sales.SalesInvoiceEntity", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemCategoryEntity", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Api.Modules.Settings.ItemEntity", b =>
                {
                    b.Navigation("AdditionalUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
