import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { useBranches } from '@/features/business'
import { useAccountTree, useGeneralLedger } from '../hooks/useAccounting'

export function GeneralLedgerPage() {
  const [accountId, setAccountId] = useState('')
  const [fromDate, setFromDate] = useState('')
  const [toDate, setToDate] = useState('')
  const [branchId, setBranchId] = useState('')
  const accounts = useAccountTree({ postingAccountsOnly: true }).data ?? []
  const branches = useBranches().data?.data.filter((branch) => branch.isActive) ?? []
  const ledger = useGeneralLedger({ accountId, fromDate, toDate, branchId }, Boolean(accountId))
  return <div className="space-y-6 p-6"><div><h1 className="text-3xl font-bold tracking-tight">General Ledger</h1><p className="text-sm text-muted-foreground">Posted activity only. Reversed journals remain visible with their offsetting reversal.</p></div><Card><CardContent className="flex flex-wrap gap-3 p-4"><select value={accountId} onChange={(event) => setAccountId(event.target.value)} className="h-9 min-w-72 rounded-md border bg-background px-3 text-sm"><option value="">Select posting account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} — {account.name}</option>)}</select><Input type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} className="w-auto" /><Input type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} className="w-auto" /><select value={branchId} onChange={(event) => setBranchId(event.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.code} — {branch.name}</option>)}</select></CardContent></Card>{ledger.isPending ? <p className="text-sm text-muted-foreground">Loading ledger…</p> : ledger.data ? <Card><CardHeader><CardTitle>{ledger.data.accountCode} — {ledger.data.accountName} <span className="ml-3 text-sm font-normal text-muted-foreground">Opening balance: {ledger.data.openingBalance.toFixed(4)}</span></CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="p-2">Date</th><th className="p-2">Journal</th><th className="p-2">Branch</th><th className="p-2">Currency</th><th className="p-2 text-right">Debit</th><th className="p-2 text-right">Credit</th><th className="p-2 text-right">Balance</th></tr></thead><tbody>{ledger.data.lines.map((line) => <tr key={`${line.journalId}-${line.entryDate}-${line.runningBalance}`} className="border-b"><td className="p-2">{line.entryDate}</td><td className="p-2"><p>{line.reference || '—'}</p><p className="text-xs text-muted-foreground">{line.journalDescription}</p></td><td className="p-2">{line.branchCode}</td><td className="p-2">{line.currencyCode}</td><td className="p-2 text-right font-mono">{line.debitBaseAmount.toFixed(4)}</td><td className="p-2 text-right font-mono">{line.creditBaseAmount.toFixed(4)}</td><td className="p-2 text-right font-mono">{line.runningBalance.toFixed(4)}</td></tr>)}</tbody></table>{ledger.data.lines.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No posted activity for the selected filters.</p>}</CardContent></Card> : <p className="text-sm text-muted-foreground">Choose an account to view its activity.</p>}</div>
}
