using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Api.Modules.Inventory;

public sealed class ProductCategoryEntityConfiguration : IEntityTypeConfiguration<ProductCategoryEntity> { public void Configure(EntityTypeBuilder<ProductCategoryEntity> b) { b.ToTable("product_categories"); b.HasKey(x => x.Id); b.Property(x => x.Name).HasMaxLength(100).IsRequired(); b.HasIndex(x => x.Name).IsUnique(); } }
public sealed class UnitOfMeasureEntityConfiguration : IEntityTypeConfiguration<UnitOfMeasureEntity> { public void Configure(EntityTypeBuilder<UnitOfMeasureEntity> b) { b.ToTable("units_of_measure"); b.HasKey(x => x.Id); b.Property(x => x.Name).HasMaxLength(100).IsRequired(); b.Property(x => x.Code).HasMaxLength(20).IsRequired(); b.HasIndex(x => x.Code).IsUnique(); } }
public sealed class ProductEntityConfiguration : IEntityTypeConfiguration<ProductEntity> { public void Configure(EntityTypeBuilder<ProductEntity> b) { b.ToTable("products"); b.HasKey(x => x.Id); b.Property(x => x.Name).HasMaxLength(250).IsRequired(); b.Property(x => x.SKU).HasMaxLength(64).IsRequired(); b.HasIndex(x => x.SKU).IsUnique(); b.Property(x => x.Barcode).HasMaxLength(64); b.HasIndex(x => x.Barcode).IsUnique().HasFilter("\"Barcode\" IS NOT NULL"); b.Property(x => x.Purpose).HasConversion<string>().HasMaxLength(20).IsRequired(); b.Property(x => x.Description).HasMaxLength(1000); b.Property(x => x.ImageReference).HasMaxLength(2048); b.HasOne(x => x.Category).WithMany(x => x.Products).HasForeignKey(x => x.CategoryId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.UnitOfMeasure).WithMany(x => x.Products).HasForeignKey(x => x.UnitOfMeasureId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class WarehouseEntityConfiguration : IEntityTypeConfiguration<WarehouseEntity> { public void Configure(EntityTypeBuilder<WarehouseEntity> b) { b.ToTable("warehouses"); b.HasKey(x => x.Id); b.Property(x => x.Code).HasMaxLength(32).IsRequired(); b.HasIndex(x => x.Code).IsUnique(); b.Property(x => x.Name).HasMaxLength(200).IsRequired(); b.HasOne(x => x.Branch).WithMany().HasForeignKey(x => x.BranchId).OnDelete(DeleteBehavior.Restrict); b.HasIndex(x => x.BranchId); } }
public sealed class StockMovementEntityConfiguration : IEntityTypeConfiguration<StockMovementEntity> { public void Configure(EntityTypeBuilder<StockMovementEntity> b) { b.ToTable("stock_movements"); b.HasKey(x => x.Id); b.Property(x => x.Type).HasConversion<string>().HasMaxLength(32).IsRequired(); b.Property(x => x.QuantityIn).HasPrecision(19, 4).IsRequired(); b.Property(x => x.QuantityOut).HasPrecision(19, 4).IsRequired(); b.Property(x => x.UnitCostBase).HasPrecision(19, 4).IsRequired(); b.Property(x => x.Reference).HasMaxLength(100); b.Property(x => x.Note).HasMaxLength(1000); b.HasIndex(x => new { x.ProductId, x.WarehouseId, x.MovementDate }); b.HasIndex(x => x.TransferId); b.HasOne(x => x.Product).WithMany(x => x.StockMovements).HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.Warehouse).WithMany(x => x.StockMovements).HasForeignKey(x => x.WarehouseId).OnDelete(DeleteBehavior.Restrict); b.HasOne(x => x.PerformedByUser).WithMany().HasForeignKey(x => x.PerformedByUserId).OnDelete(DeleteBehavior.Restrict); } }
