using Api.Modules.Branch;
using Api.Modules.User;

namespace Api.Modules.Inventory;

public sealed class ProductCategoryEntity { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = string.Empty; public bool IsActive { get; set; } = true; public ICollection<ProductEntity> Products { get; set; } = new List<ProductEntity>(); }
public sealed class UnitOfMeasureEntity { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public bool IsActive { get; set; } = true; public ICollection<ProductEntity> Products { get; set; } = new List<ProductEntity>(); }
public sealed class ProductEntity { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = string.Empty; public string SKU { get; set; } = string.Empty; public string? Barcode { get; set; } public Guid CategoryId { get; set; } public ProductCategoryEntity Category { get; set; } = null!; public Guid UnitOfMeasureId { get; set; } public UnitOfMeasureEntity UnitOfMeasure { get; set; } = null!; public ProductPurpose Purpose { get; set; } public bool TrackInventory { get; set; } = true; public bool IsActive { get; set; } = true; public string? Description { get; set; } public string? ImageReference { get; set; } public ICollection<StockMovementEntity> StockMovements { get; set; } = new List<StockMovementEntity>(); }
public sealed class WarehouseEntity { public Guid Id { get; set; } = Guid.NewGuid(); public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public Guid BranchId { get; set; } public BranchEntity Branch { get; set; } = null!; public bool IsActive { get; set; } = true; public ICollection<StockMovementEntity> StockMovements { get; set; } = new List<StockMovementEntity>(); }
public sealed class StockMovementEntity { public Guid Id { get; set; } = Guid.NewGuid(); public Guid ProductId { get; set; } public ProductEntity Product { get; set; } = null!; public Guid WarehouseId { get; set; } public WarehouseEntity Warehouse { get; set; } = null!; public StockMovementType Type { get; set; } public DateOnly MovementDate { get; set; } public decimal QuantityIn { get; set; } public decimal QuantityOut { get; set; } public decimal UnitCostBase { get; set; } public string? Reference { get; set; } public string? Note { get; set; } public Guid? TransferId { get; set; } public Guid PerformedByUserId { get; set; } public UserEntity PerformedByUser { get; set; } = null!; public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; }
public enum ProductPurpose { Resale, Consumable, Both }
public enum StockMovementType { OpeningStock, PositiveAdjustment, NegativeAdjustment, TransferOut, TransferIn }
